# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from pessoa import Pessoa
from cadastro import Cadastro


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo_cadastro = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_cadastro.setGeometry(QtCore.QRect(170, 0, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_titulo_cadastro.setFont(font)
        self.label_titulo_cadastro.setObjectName("label_titulo_cadastro")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(40, 90, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_endereco = QtWidgets.QLabel(self.centralwidget)
        self.label_endereco.setGeometry(QtCore.QRect(40, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_endereco.setFont(font)
        self.label_endereco.setObjectName("label_endereco")
        self.label_cpf = QtWidgets.QLabel(self.centralwidget)
        self.label_cpf.setGeometry(QtCore.QRect(40, 170, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cpf.setFont(font)
        self.label_cpf.setObjectName("label_cpf")
        self.label_nascimento = QtWidgets.QLabel(self.centralwidget)
        self.label_nascimento.setGeometry(QtCore.QRect(40, 210, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nascimento.setFont(font)
        self.label_nascimento.setObjectName("label_nascimento")
        self.input_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nome.setGeometry(QtCore.QRect(220, 80, 281, 31))
        self.input_nome.setObjectName("input_nome")
        self.input_endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.input_endereco.setGeometry(QtCore.QRect(220, 120, 281, 31))
        self.input_endereco.setObjectName("input_endereco")
        self.input_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cpf.setGeometry(QtCore.QRect(220, 160, 281, 31))
        self.input_cpf.setObjectName("input_cpf")
        self.input_nascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nascimento.setGeometry(QtCore.QRect(220, 200, 281, 31))
        self.input_nascimento.setObjectName("input_nascimento")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 310, 541, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.button_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.button_cadastrar.setGeometry(QtCore.QRect(220, 260, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_cadastrar.setFont(font)
        self.button_cadastrar.setObjectName("button_cadastrar")
        self.label_titulo_busca = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_busca.setGeometry(QtCore.QRect(250, 340, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_titulo_busca.setFont(font)
        self.label_titulo_busca.setObjectName("label_titulo_busca")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 390, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.search_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.search_cpf.setGeometry(QtCore.QRect(130, 380, 171, 28))
        self.search_cpf.setObjectName("search_cpf")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 450, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 490, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 530, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.output_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.output_nome.setGeometry(QtCore.QRect(220, 440, 281, 28))
        self.output_nome.setObjectName("output_nome")
        self.output_endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.output_endereco.setGeometry(QtCore.QRect(220, 480, 281, 28))
        self.output_endereco.setObjectName("output_endereco")
        self.output_nascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.output_nascimento.setGeometry(QtCore.QRect(220, 520, 281, 28))
        self.output_nascimento.setObjectName("output_nascimento")
        self.button_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.button_buscar.setGeometry(QtCore.QRect(340, 380, 81, 28))
        self.button_buscar.setObjectName("button_buscar")
        self.label_titulo_cadastro.raise_()
        self.label_name.raise_()
        self.label_cpf.raise_()
        self.label_nascimento.raise_()
        self.label_endereco.raise_()
        self.input_nome.raise_()
        self.input_endereco.raise_()
        self.input_cpf.raise_()
        self.input_nascimento.raise_()
        self.line.raise_()
        self.button_cadastrar.raise_()
        self.label_titulo_busca.raise_()
        self.label.raise_()
        self.search_cpf.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.output_nome.raise_()
        self.output_endereco.raise_()
        self.output_nascimento.raise_()
        self.button_buscar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Modificações
        self.cad = Cadastro()
        self.button_cadastrar.clicked.connect(self.botaoCadastra)
        self.button_buscar.clicked.connect(self.botaoBusca)


    def botaoCadastra(self): 
        nome = self.input_nome.text()
        endereco = self.input_endereco.text()
        cpf = self.input_cpf.text()
        nascimento = self.input_nascimento.text()

        if not(nome == '' or endereco == '' or cpf == '' or nascimento == ''):
            p = Pessoa(nome, endereco, cpf, nascimento)

            if (self.cad.cadastra(p)):
                QMessageBox.information(None, "POOII", "Cadastro realizado com sucesso!!")
                self.input_nome.setText('')
                self.input_endereco.setText('')
                self.input_cpf.setText('')
                self.input_nascimento.setText('')
            else:
                QMessageBox.information(None, "POOII", "O CPF informado já existe!!")
        else:
            QMessageBox.information(None, "POOII", "Todos os valores devem ser preenchidos!!")


    def botaoBusca(self):
        cpf = self.search_cpf.text()
        pessoa = self.cad.busca(cpf)

        if (pessoa):
            self.output_nome.setText(pessoa.nome)
            self.output_endereco.setText(pessoa.endereco)
            self.output_nascimento.setText(pessoa.nascimento)
        else:
            QMessageBox.information(None, "POOII", "CPF não encontrado")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo_cadastro.setText(_translate("MainWindow", "Cadastro de Pessoas"))
        self.label_name.setText(_translate("MainWindow", "Nome"))
        self.label_endereco.setText(_translate("MainWindow", "Endereço"))
        self.label_cpf.setText(_translate("MainWindow", "CPF"))
        self.label_nascimento.setText(_translate("MainWindow", "Data de nascimento"))
        self.button_cadastrar.setText(_translate("MainWindow", "cadastrar!"))
        self.label_titulo_busca.setText(_translate("MainWindow", "Busca"))
        self.label.setText(_translate("MainWindow", "CPF"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.label_3.setText(_translate("MainWindow", "Endereço"))
        self.label_4.setText(_translate("MainWindow", "Data de nascimento"))
        self.button_buscar.setText(_translate("MainWindow", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
